export const mockEmails = [
  {
    id: "1",
    from: "Sarah Johnson",
    email: "sarah.j@company.com",
    subject: "Q1 Marketing Strategy Review",
    snippet:
      "Hi team, I've compiled the Q1 results and would like to schedule a review meeting next week...",
    date: new Date("2026-01-17T09:30:00"),
    unread: true,
    category: "inbox",
    starred: true,
    avatar: "SJ",
  },
  {
    id: "2",
    from: "LinkedIn",
    email: "notifications@linkedin.com",
    subject: "You appeared in 12 searches this week",
    snippet:
      "Your profile is getting noticed! See who's viewing your profile and expand your network...",
    date: new Date("2026-01-17T08:15:00"),
    unread: true,
    category: "social",
    starred: false,
    avatar: "LI",
  },
  {
    id: "3",
    from: "Amazon",
    email: "shipment@amazon.com",
    subject: "Your order has been shipped",
    snippet:
      "Good news! Your package is on the way. Track your shipment with the link below...",
    date: new Date("2026-01-16T18:45:00"),
    unread: false,
    category: "promotions",
    starred: false,
    avatar: "AZ",
  },
  {
    id: "4",
    from: "Michael Chen",
    email: "m.chen@tech.io",
    subject: "Re: API Integration Documentation",
    snippet:
      "Thanks for the quick response! The implementation looks good. I've added a few suggestions...",
    date: new Date("2026-01-16T15:20:00"),
    unread: false,
    category: "inbox",
    starred: true,
    avatar: "MC",
  },
  {
    id: "5",
    from: "Google Calendar",
    email: "calendar@google.com",
    subject: "Reminder: Team Standup in 30 minutes",
    snippet: "This is a reminder that Team Standup starts at 10:00 AM today...",
    date: new Date("2026-01-17T09:30:00"),
    unread: true,
    category: "inbox",
    starred: false,
    avatar: "GC",
  },
  {
    id: "6",
    from: "GitHub",
    email: "notifications@github.com",
    subject: "[PR] Feature/user-authentication merged",
    snippet:
      "Your pull request #234 was successfully merged into main by @john-doe...",
    date: new Date("2026-01-16T22:10:00"),
    unread: false,
    category: "social",
    starred: false,
    avatar: "GH",
  },
  {
    id: "7",
    from: "Stripe",
    email: "receipts@stripe.com",
    subject: "Receipt for your subscription renewal",
    snippet:
      "Your subscription has been renewed for $29.99. Invoice #INV-2026-0117...",
    date: new Date("2026-01-15T14:00:00"),
    unread: false,
    category: "promotions",
    starred: false,
    avatar: "ST",
  },
  {
    id: "8",
    from: "Emily Rodriguez",
    email: "e.rodriguez@design.co",
    subject: "Design System Updates - Review Needed",
    snippet:
      "Hey! I've updated the component library with the new color palette and typography...",
    date: new Date("2026-01-15T11:30:00"),
    unread: false,
    category: "inbox",
    starred: true,
    avatar: "ER",
  },
];

export const mockEvents = [
  {
    id: "1",
    title: "Team Standup",
    date: new Date("2026-01-17T10:00:00"),
    endDate: new Date("2026-01-17T10:30:00"),
    meetingLink: "https://meet.google.com/abc-defg-hij",
    attendees: ["team@company.com"],
    color: "chart-1",
    type: "today",
  },
  {
    id: "2",
    title: "Client Presentation",
    date: new Date("2026-01-17T14:00:00"),
    endDate: new Date("2026-01-17T15:30:00"),
    meetingLink: "https://zoom.us/j/123456789",
    attendees: ["client@acme.com", "sales@company.com"],
    color: "chart-2",
    type: "today",
  },
  {
    id: "3",
    title: "Product Strategy Meeting",
    date: new Date("2026-01-18T09:00:00"),
    endDate: new Date("2026-01-18T10:30:00"),
    meetingLink: "https://meet.google.com/xyz-abcd-efg",
    attendees: ["product@company.com"],
    color: "chart-3",
    type: "upcoming",
  },
  {
    id: "4",
    title: "1:1 with Manager",
    date: new Date("2026-01-18T15:00:00"),
    endDate: new Date("2026-01-18T15:30:00"),
    meetingLink: null,
    attendees: ["manager@company.com"],
    color: "chart-4",
    type: "upcoming",
  },
  {
    id: "5",
    title: "Design Review",
    date: new Date("2026-01-20T11:00:00"),
    endDate: new Date("2026-01-20T12:00:00"),
    meetingLink: "https://meet.google.com/design-review-123",
    attendees: ["design@company.com"],
    color: "chart-1",
    type: "upcoming",
  },
  {
    id: "6",
    title: "Sprint Planning",
    date: new Date("2026-01-20T14:00:00"),
    endDate: new Date("2026-01-20T16:00:00"),
    meetingLink: "https://meet.google.com/sprint-plan-456",
    attendees: ["dev-team@company.com"],
    color: "chart-2",
    type: "upcoming",
  },
  {
    id: "7",
    title: "Coffee Chat",
    date: new Date("2026-01-21T10:30:00"),
    endDate: new Date("2026-01-21T11:00:00"),
    meetingLink: null,
    attendees: ["colleague@company.com"],
    color: "chart-5",
    type: "upcoming",
  },
  {
    id: "8",
    title: "All Hands Meeting",
    date: new Date("2026-01-22T13:00:00"),
    endDate: new Date("2026-01-22T14:00:00"),
    meetingLink: "https://meet.google.com/all-hands-789",
    attendees: ["everyone@company.com"],
    color: "chart-3",
    type: "upcoming",
  },
];
